services:
  app:
    build: .
    container_name: tourify
    image: belall0/tourify:latest
    ports:
      - '80:80'
      - '443:443'
    env_file:
      - .env
    volumes:
      - '/etc/letsencrypt:/etc/letsencrypt:ro'
